### ISSUE TITLE
Struttura esame veloce

### ISSUE THREAD

**Issue by marcoscale98** [stefa168/guida_degli_studenti_di#12]
Proporrei di creare una lista degli esami con associato il tipo di esame (Scritto, orale, con o senza progetto). Insomma, informazioni che stanno in una riga

# Obiettivo
- visione d'insieme sugli esami
- per capire se hanno il progetto oppure no
- per valutare il proprio carico di lavoro durante il semestre

**Comment by federicotorrielli** [comment]
+1, ci starebbe anche mettere la difficoltà e i requisiti per passarlo, magari con qualche link a appunti o domande, se esistono

**Comment by marcoscale98** [comment]
> +1, ci starebbe anche mettere la difficoltà e i requisiti per passarlo, magari con qualche link a appunti o domande, se esistono

Requisiti per passarlo cosa intendi? Ad esempio i corsi da ritenersi come prerequisiti?

Comunque la mia idea era di creare uno strumento per una rapida visione d'insieme su tutti gli esami. Ad esempio a me servirà per settembre per gestire il carico di lavoro sul prossimo semestre (non voglio mettermi troppi progetti)

**Comment by marcoscale98** [comment]
Quale strumento potremmo usare? Tabelle in markdown?

**Comment by federicotorrielli** [comment]
> Quale strumento potremmo usare? Tabelle in markdown?

Direi che è l'opzione più conforme a quanto già facciamo in repository, per me va bene.

**Comment by federicotorrielli** [comment]
@marcoscale98 grazie per la PR, in questi giorni aggiungo contenuto
