### ISSUE TITLE
Aggiunta .gitignore

### ISSUE THREAD

**Issue by federicotorrielli** [stefa168/guida_degli_studenti_di#39]
Dovremmo aggiungere un file .gitignore per ignorare estensioni tipo .DS_Store etc etc etc...

**Comment by lory9894** [comment]
Si può fare, carico io un gitignore, però non saprei quali tipi di file inserire.
Di sicuro tutti i file di configurazioni di vscode e di intellij.
Inoltre inserisco i file derivanti dalla compilazione di Latexmk ..... anche se tutti usano overleaf .

**Comment by federicotorrielli** [comment]
Chiudo con #41
