### ISSUE TITLE
Appunti segnati errati

### ISSUE THREAD

**Issue by lory9894** [stefa168/guida_degli_studenti_di#68]
Stavo guardando tra gli appunti ed ho notato che [questi appunti di reti2](https://github.com/stefa168/guida_degli_studenti_di/blob/master/Materie/RETI2/Appunti/Appunti%20reti-2.txt) sono in realtà appunti di Reti 1

**Comment by federicotorrielli** [comment]
@lory9894 posso chiudere?

**Comment by lory9894** [comment]
@federicotorrielli Essendo stato mergato si
